# configuration.yaml file

accounts:
  - account_name: "Example Account Name" # account_name is arbitrary, simply used for printing to the console
    api_key: 'XxxxXXXXXxxxxXXXXxxxxXXXXX'
    api_secret: 'YYYYyyyyyYYYYyyyyYYYYYyyy'
    anti_algo_subaccount_name: 'EMPTY SUB ACCOUNT NAME' # anti_algo_subaccount_name is only necessary if
                                                        # re-balancing portfolio.
    subaccount_names: # The script will auto populate with all sub accounts,
                      #  or you can uncomment the below and specify the sub account names to use
#      - 'SUB ACCOUNT NAME 1'
#      - 'SUB ACCOUNT NAME 2'
#      - 'SUB ACCOUNT NAME 3'

#  - account_name: "" # Uncomment out this and add as many blocks as you like to manage more than one FTX Account
#    api_key: ''
#    api_secret: ''
#    anti_algo_subaccount_name: ''
#    subaccount_names:
#      - ''
#      - ''



settings:
  # Ideal Percentages should all add up to 100%
  ideal_btc_collateral_percentage: 30
  ideal_usd_collateral_percentage: 50
  ideal_eth_collateral_percentage: 20
  ideal_ftt_collateral_percentage: 0